### ISSUE TITLE
Ping coordinates documentation 

### ISSUE THREAD

**Issue by steelwolf180** [Asymmetrik/ngx-leaflet-d3#6]
Hi my name's Max, first of all i would like to thank you for providing the library and documentation for integration with angular 5. 

I was trying to use the library for the ping feature. Which  would be great that you include a comment. In the ping code to say that the format of the coordinates is longitude by latitude. Cause i was having troubles in figuring it out based upon the documentation

`private generatePings() {

	this.leafletPingObserver.next({
		data: [ 40, 50 ] // coordinates is in longitude by latitude
	});

	setTimeout(this.generatePings.bind(this), 100);
}`

**Comment by reblace** [comment]
Updating docs in next release.
