### ISSUE TITLE
Invalid module name

### ISSUE THREAD

**Issue by vitosalvia** [Asymmetrik/ngx-leaflet-d3#7]
I have an error trying to run the applicaton : 
ERROR in node_modules/@asymmetrik/leaflet-d3/index.d.ts(3,16): error TS2665: Invalid module name in augmentation. Module 'leaflet' resolves to an untyped module : 
node_modules/leaflet/dist/leaflet-src.js', which cannot be augmented.

**Comment by reblace** [comment]
I would assume you are missing the leaflet types. Make sure you've installed `@types/leaflet`
